#pragma once

#include <enum.h>


namespace ieml::AST {

BETTER_ENUM(DeclarationType, char, COMPONENT, NODE, PARANODE, LINK, WORD, INFLECTION, AUXILIARY, JUNCTION, LANGUAGE, TABLE)
BETTER_ENUM(PathType, char, ROOT, JUNCTION, PARADIGM, ROLE, WORD, AUXILIARY, INFLECTION)

}