ARG NB_CORES=1

# build WASM target using emscripten 
# the generated .js and .wasm are generated in /libieml/build/binding/wasm/parser_wasm.{js,wasm}
FROM emscripten/emsdk:3.1.7 AS build_wasm
WORKDIR /libieml

RUN apt-get update && \
    apt-get install -y default-jre git

# library basic
COPY CMakeLists.txt /libieml/CMakeLists.txt
COPY IEMLConfig.h.in /libieml/IEMLConfig.h.in
COPY cmake /libieml/cmake 
COPY thirdparty /libieml/thirdparty 
COPY include /libieml/include
COPY src /libieml/src
# wasm related
COPY binding/wasm /libieml/binding/wasm
# need to add this pkg-config file because emscripten do not provide it and antlr needs it
COPY binding/wasm/uuid.pc $EMSDK/upstream/emscripten/cache/sysroot/lib/pkgconfig/

# build WASM
RUN mkdir build && \
    cd build && \
    emcmake cmake -DBUILD_WASM:bool=True .. &&\
    emmake make -j $NB_CORES

# Building the python wheels and test suite
# I tried to reuse the last image but I didn't succeed to make it work
FROM python:3.8-slim
WORKDIR /libieml

WORKDIR /libieml

RUN apt-get update && \
    apt-get install -y git g++ cmake default-jre pkg-config uuid-dev 

# library basic
COPY CMakeLists.txt /libieml/CMakeLists.txt
COPY IEMLConfig.h.in /libieml/IEMLConfig.h.in
COPY cmake /libieml/cmake 
COPY thirdparty /libieml/thirdparty 
COPY include /libieml/include
COPY src /libieml/src
# python binding related
COPY setup.py /libieml/setup.py
COPY binding/python /libieml/binding/python
# test related
COPY test /libieml/test
COPY assets /libieml/assets

# build test and python binding
RUN CMAKE_BUILD_PARALLEL_LEVEL=$NB_CORES CMAKE_ARGS="-DBUILD_TEST=True" python3.8 setup.py bdist_wheel

# dist folder will contains the builded artifacts
RUN mkdir /dist
# copy wasm binding
COPY --from=build_wasm /libieml/build/binding/wasm/parser_wasm.* /dist/
# copy python wheel
RUN cp /libieml/dist/*.whl /dist/ 
RUN ls /dist/

CMD ["/libieml/build/temp.linux-x86_64-3.8/test/libieml_test"]