version: "3.3"
services:
  test:
    build:
      context: .
      dockerfile: ./Dockerfile_run_test
    volumes:
      # - ./build_test:/libieml/build
      - ./build_cache:/libieml/build_cache
  build_python:
    build:
      context: .
      dockerfile: ./Dockerfile_build_python
  build_wasm:
    build:
      context: .
      dockerfile: ./Dockerfile_build_wasm
    volumes:
      - ./build_wasm:/libieml/build
      - ./build_cache:/libieml/build_cache
