ARG NB_CORES=1

# build WASM target using emscripten 
# the generated .js and .wasm are generated in /libieml/build/binding/wasm/parser_wasm.{js,wasm}
FROM emscripten/emsdk:3.1.7

WORKDIR /libieml
RUN apt-get update && apt-get install -y default-jre git


COPY CMakeLists.txt /libieml/CMakeLists.txt
COPY IEMLConfig.h.in /libieml/IEMLConfig.h.in
COPY binding/wasm /libieml/binding/wasm
COPY cmake /libieml/cmake 
COPY thirdparty /libieml/thirdparty 
COPY include /libieml/include
COPY src /libieml/src

# need to add this pkg-config file because emscripten lack to provide it
COPY binding/wasm/uuid.pc $EMSDK/upstream/emscripten/cache/sysroot/lib/pkgconfig/

RUN mkdir build && \
    cd build && \
    emcmake cmake -DBUILD_WASM:bool=True .. &&\
    emmake make -j $NB_CORES

