version: "3.3"
services:
  test:
    build:
      context: .
      dockerfile: ./Dockerfile_run_test
  build_python:
    build:
      context: .
      dockerfile: ./Dockerfile_build_python
  build_wasm:
    build:
      context: .
      dockerfile: ./Dockerfile_build_wasm
    volumes:
      - ./build_wasm:/libieml/build
