ARG NB_CORES=1
FROM ghcr.io/intlekt/intlekt_test_builder:latest AS build_test
WORKDIR /libieml

COPY CMakeLists.txt /libieml/CMakeLists.txt
COPY IEMLConfig.h.in /libieml/IEMLConfig.h.in
COPY cmake /libieml/cmake 
COPY thirdparty /libieml/thirdparty 
COPY include /libieml/include
COPY src /libieml/src
COPY test /libieml/test
COPY assets /libieml/assets

CMD mkdir -p build && \
    cd build && \
    cmake -DBUILD_TEST:BOOL=TRUE ..&& \
    cmake --build . -j $NB_CORES && /libieml/build/test/libieml_test