ARG NB_CORES=1
FROM ghcr.io/intlekt/intlket_wasm_builder:latest AS build_wasm
WORKDIR /libieml

COPY CMakeLists.txt /libieml/CMakeLists.txt
COPY IEMLConfig.h.in /libieml/IEMLConfig.h.in
COPY cmake /libieml/cmake 
COPY thirdparty /libieml/thirdparty 
COPY include /libieml/include
COPY src /libieml/src
COPY build_wasm.sh /libieml/build_wasm.sh
# wasm related
COPY binding/wasm /libieml/binding/wasm
# need to add this pkg-config file because emscripten do not provide it and antlr needs it
COPY binding/wasm/uuid.pc $EMSDK/upstream/emscripten/cache/sysroot/lib/pkgconfig/

VOLUME ["/libieml/build"]

CMD ["bash", "./build_wasm.sh"]