name: Release

on:
  workflow_dispatch:
    tags:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Build the Docker Image
        run: docker build . --file Dockerfile_build_all_run_test --tag build_image

      - name: Copy files to local host
        run: >
          id=$(docker create build_image) &&
          docker cp $id:/dist dist &&
          docker rm -v $id

      - name: Create release
        uses: ncipollo/release-action@v1
        with: 
          artifacts: "dist/*"
          body: "WASM and Python3.8 cp38-cp38-linux_x86_64 bindings"
          token: ${{ secrets.GITHUB_TOKEN }}
